# Generated by Django 4.2.13 on 2024-06-25 08:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memory',
            options={},
        ),
        migrations.RemoveField(
            model_name='memory',
            name='date',
        ),
        migrations.RemoveField(
            model_name='memory',
            name='folder',
        ),
        migrations.RemoveField(
            model_name='memory',
            name='google_drive_link',
        ),
        migrations.RemoveField(
            model_name='memory',
            name='user',
        ),
        migrations.AddField(
            model_name='memory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memory',
            name='drive_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='memory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='memory',
            name='image',
            field=models.ImageField(upload_to='memory_images'),
        ),
        migrations.DeleteModel(
            name='Folder',
        ),
    ]
